### ISSUE TITLE
Upcoming changes to netket

### ISSUE THREAD

**Issue by PhilipVinc** [BoothGroup/GPSKet#3]
Hi guys, do you still use this? I'm planning a few minor changes to the internals of netket and was looking at whether they impact you, but the tests don't pass anymore so it's hard for me to get an idea of what to fix..

**Comment by maxbortone** [comment]
Ciao @PhilipVinc, yes we are still using and developing GPSKet. Our test are useless at the moment, sorry for that. What are you planning on changing in NetKet?

**Comment by PhilipVinc** [comment]
Ciao! 

The main possibly 'breaking' change is related to how `@dispatch` rules are defined, to simplify them considerably and removing those horrible `dispatch.TrueT` and `use covariance` which are confusing. Probably it would mean requiring users/you to change the dispatch signatures to 

```python
@expect.dispatch
def expect(vs: MySpecialMCState, op: MyOperator, chunk_size: None):
    pass

@expect_and_grad.dispatch
def expect_and_grad(vs: MySpecialMCState, op: MyOperator, chunk_size: None, **kwargs):
   pass
```

but I'm not 100% sure of what will end up. I'd like to avoid breaking people's code (including yours) and the best way to take it into consideration is if I can run your tests, for example by running `pytest` to know if I am breaking your code or not...

That's not important, but as I look at other's people code to inform what to change in netket and minimise pain downstream, it's useful for me to be able to know if your code is affected by my changes.
